<?php
declare(strict_types=1);
namespace OtpAuth;
use PDO;
final class WidgetController
{
    public function __construct(private PDO $db,private ApiKeyService $keys,private RateLimiter $limiter,private AbuseLimiter $abuse,private SettingsService $settings,private OtpService $otp) {}
    public function handle(string $action): never
    {
        $data=Request::json();$publicId=trim((string)($data['project']??$data['project_id']??''));if($publicId===''||strlen($publicId)>64)$this->fail('project_required','Public project ID is required.',400);$key=$this->keys->authenticatePublicProject($publicId);if(!$key)$this->fail('invalid_project','Project is unavailable for widget use.',403);$projectId=(int)$key['project_id'];$mode=strtolower(trim((string)($data['mode']??'test')));if(!in_array($mode,['test','production'],true))$this->fail('invalid_mode','Invalid widget environment.',400);if($mode==='production'&&!$this->productionEnabled($projectId))$this->fail('production_not_enabled','Production mode is not enabled for this project.',403);$origin=$this->origin();$allowed=$this->allowedOrigins($projectId,(string)$key['website_domain']);if($origin===''||!in_array($origin,$allowed,true))$this->fail('origin_not_allowed','This website is not authorized for this project.',403);$this->cors($origin);if(!$this->widgetEnabled($projectId))$this->fail('widget_disabled','Widget integration is disabled.',403);
        $email=Validation::email($data['email']??null);$purpose=Validation::purpose($data['purpose']??'generic');$emailHash=hash('sha256',$email);$apiKeyId=(int)$key['id'];$ip=Request::ip();$this->abuse->allow('widget:ip:'.$ip,Config::int('OTP_MAX_GLOBAL_IP_REQUESTS_PER_HOUR',50),3600)||$this->fail('ip_rate_limit_exceeded','Too many requests.',429);$this->abuse->allow('widget:email:'.$emailHash,Config::int('OTP_MAX_GLOBAL_EMAIL_REQUESTS_PER_HOUR',20),3600)||$this->fail('email_rate_limit_exceeded','Too many requests for this recipient.',429);$this->limiter->allow($apiKeyId,'widget:'.$mode.':'.$ip.':hour',Config::int('OTP_MAX_PROJECT_REQUESTS_PER_HOUR',100),3600)||$this->fail('rate_limit_exceeded','Project rate limit exceeded.',429);
        if($action==='verify'){$otp=Validation::otp($data['otp']??null);$requestId=isset($data['request_id'])?Validation::requestId($data['request_id']):null;$this->limiter->allow($apiKeyId,'widget:verify:'.$emailHash,Config::int('OTP_MAX_VERIFY_REQUESTS_PER_HOUR',20),3600)||$this->fail('verify_rate_limit_exceeded','Too many verification attempts.',429);$result=$this->otp->verify($email,$purpose,$otp,$apiKeyId,$requestId);if($result['verified'])Response::success(['verified'=>true,'request_id'=>$result['request_id'],'mode'=>$mode]);$errors=['expired'=>['otp_expired','OTP has expired.',400],'too_many_attempts'=>['otp_attempts_exceeded','Maximum OTP verification attempts exceeded.',429],'invalid'=>['invalid_otp','Invalid OTP.',400]];[$code,$message,$status]=$errors[$result['reason']]??['otp_verification_failed','OTP verification failed.',400];$this->fail($code,$message,$status);}
        if($action==='request'||$action==='resend'){if($action==='resend'){$this->limiter->allow($apiKeyId,'widget:resend:'.$emailHash,1,Config::int('OTP_RESEND_COOLDOWN_SECONDS',60))||$this->fail('resend_cooldown','Please wait before requesting another OTP.',429);$this->limiter->allow($apiKeyId,'widget:resend-hour:'.$emailHash,Config::int('OTP_MAX_RESENDS_PER_HOUR',5),3600)||$this->fail('resend_rate_limit_exceeded','Resend rate limit exceeded.',429);}try{$result=$this->otp->request($email,$purpose,$apiKeyId,$projectId);}catch(\Throwable $e){$this->fail('otp_delivery_failed','OTP delivery failed.',502);}Response::success(['message'=>'OTP sent. It may take a few seconds to arrive.','request_id'=>$result['request_id'],'expires_at'=>$result['expires_at'],'mode'=>$mode],201);}
        $this->fail('unknown_action','Unknown widget action.',404);
    }
    private function productionEnabled(int $projectId): bool{$s=$this->db->prepare('SELECT production_enabled FROM project_widget_settings WHERE project_id=?');$s->execute([$projectId]);return(int)$s->fetchColumn()===1;}
    private function widgetEnabled(int $projectId): bool{$s=$this->db->prepare('SELECT widget_enabled FROM project_widget_settings WHERE project_id=?');$s->execute([$projectId]);$v=$s->fetchColumn();return $v===false||((int)$v===1);}
    private function allowedOrigins(int $projectId,string $domain): array{$s=$this->db->prepare('SELECT allowed_origins FROM project_widget_settings WHERE project_id=?');$s->execute([$projectId]);$value=(string)($s->fetchColumn()??'');$origins=array_values(array_filter(array_map('trim',preg_split('/\R/',$value)?:[])));if(!$origins&&$domain!=='')$origins=['https://'.strtolower($domain),'http://'.strtolower($domain)];return $origins;}
    private function origin(): string{return trim((string)($_SERVER['HTTP_ORIGIN']??''));}
    private function cors(string $origin): void{header('Access-Control-Allow-Origin: '.$origin);header('Vary: Origin');header('Access-Control-Allow-Credentials: false');header('Access-Control-Allow-Headers: Content-Type');header('Access-Control-Allow-Methods: POST, OPTIONS');}
    private function fail(string $code,string $message,int $status): never{Response::error($code,$message,$status);}
}
